#:schema node_modules/wrangler/config-schema.json
name = "sublink-fiat24"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "15099856ba9244d2ba5f115d6f57961d" }
]

[assets]
directory = "./public"
